#server
server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 100
  servlet:
    context-path: /

#datasource,mybatis,thymeleaf
spring:
  datasource:
    url: jdbc:mysql:///jtsys?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/pages/
    cache: false
mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:/mapper/*/*.xml

#log
logging:
  level:
    com.cy: debug

#page
db.page:
  pageSize: 5

#pageHelper
pagehelper:
  helperDialect: mysql
  reasonable: true